"""Fit ANFIS against reproducible synthetic targets from a planted TSK model.

This is an implementation smoke run, not a calibration-data training
pipeline. Target-distribution design and snapshot labels are owned by Issue #57.
"""

from __future__ import annotations

import argparse
import json
from typing import Final

import numpy as np

from superconducted.fuzzy.defuzzification import NieTanDefuzzifier, WeightedAverageDefuzzifier
from superconducted.fuzzy.membership import GaussianMF, IntervalGaussianMF
from superconducted.fuzzy.tsk import TSKRuleBase
from superconducted.interfaces import MembershipFunction
from superconducted.training import HybridANFISTrainer, TrainingSet

_DEFAULT_ROWS: Final[int] = 96
_DEFAULT_SEED: Final[int] = 0


def _rule_base(interval_type2: bool, *, consequent_init: str) -> TSKRuleBase:
    memberships: list[list[MembershipFunction]]
    if interval_type2:
        memberships = [
            [IntervalGaussianMF(-1.0, 0.45, 0.8), IntervalGaussianMF(1.0, 0.45, 0.8)],
            [IntervalGaussianMF(-1.0, 0.45, 0.8), IntervalGaussianMF(1.0, 0.45, 0.8)],
        ]
    else:
        memberships = [
            [GaussianMF(-1.0, 0.7), GaussianMF(1.0, 0.7)],
            [GaussianMF(-1.0, 0.7), GaussianMF(1.0, 0.7)],
        ]
    return TSKRuleBase.from_grid(memberships, output_dim=1, consequent_init=consequent_init)


def _synthetic_data(rows: int, seed: int, interval_type2: bool) -> tuple[TSKRuleBase, TrainingSet]:
    rng = np.random.default_rng(seed)
    planted = _rule_base(interval_type2, consequent_init="zeros")
    for rule in planted.rules:
        rule.consequent_params[:] = rng.normal(0.0, 0.5, size=rule.consequent_params.shape)
    features = rng.uniform(-2.0, 2.0, size=(rows, planted.input_dim))
    defuzzifier = NieTanDefuzzifier() if interval_type2 else WeightedAverageDefuzzifier()
    targets = np.asarray([defuzzifier.defuzzify(planted.evaluate(feature)) for feature in features])
    return planted, TrainingSet(features, targets)


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python scripts/train_anfis.py",
        description="Fit ANFIS to seeded synthetic labels generated by a planted TSK model.",
    )
    parser.add_argument("--rows", type=int, default=_DEFAULT_ROWS, help="Synthetic row count.")
    parser.add_argument("--seed", type=int, default=_DEFAULT_SEED, help="Random seed.")
    parser.add_argument("--epochs", type=int, default=0, help="Premise optimization epochs.")
    parser.add_argument(
        "--it2", action="store_true", help="Generate interval Type-2 Nie-Tan targets."
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    args = _build_arg_parser().parse_args(argv)
    if args.rows < 12:
        raise ValueError("--rows must be at least 12 for the four-rule linear consequent system")
    if args.epochs < 0:
        raise ValueError("--epochs must be non-negative")
    planted, data = _synthetic_data(args.rows, args.seed, args.it2)
    initial = _rule_base(args.it2, consequent_init="zeros")
    result = HybridANFISTrainer(epochs=args.epochs, seed=args.seed).fit(initial, data)
    print(
        json.dumps(
            {
                "data_source": "planted_tsk_synthetic",
                "interval_type2": args.it2,
                "rows": data.n_rows,
                "input_dim": planted.input_dim,
                "output_dim": planted.output_dim,
                "epochs": args.epochs,
                "train_rmse": result.train_rmse.tolist(),
                "parameter_count": result.parameter_count.total,
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
